[tox]
requires = tox>=4
env_list = ansible216

[testenv]
basepython = python3.12

deps =
    ansible216: ansible-core == 2.16.*
    ansible217: ansible-core == 2.17.*
    ansible218: ansible-core == 2.18.*
    ansible219: ansible-core == 2.19.*
    ansible220: ansible-core == 2.20.*
    winrm: pywinrm[credssp,kerberos]

[testenv:ansible{216,217,218,219,220}-lint]
deps =
    {[testenv]deps}
    ansible-lint == 26.*
    yamllint

commands =
    yamllint .
    ansible-lint

[testenv:ansible{216,217,218,219,220}{,-winrm}]
deps =
    {[testenv]deps}
    -rtox-requirements.txt

commands = molecule {posargs: test}

passenv =
    MOLECULE_PLAYBOOK
    NAMESPACE
    IMAGE
    TAG

setenv =
    ANSIBLE_FORCE_COLOR=1
    PY_COLORS=1
    TOX_ENVNAME=-{envname}
    winrm: OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
