---
- name: 'Converge'
  hosts: all
  vars:
    windows_exporter_tls_server_config:
      cert_file: 'C:\Program Files\windows_exporter\ssl\windows_exporter.cert'
      key_file: 'C:\Program Files\windows_exporter\ssl\windows_exporter.key'
    windows_exporter_basic_auth_users:
      newuser1: 'newpassword1'

  pre_tasks:
    - name: 'Create a certificate directory'
      ansible.windows.win_file:
        path: '{{ windows_exporter_tls_server_config.cert_file | win_dirname }}'
        state: 'directory'

    - name: 'Copy the certificate and key'
      ansible.builtin.copy:
        src: '{{ cert.src }}'
        dest: '{{ cert.dest }}'
        mode: 0644
      loop:
        - src: '/tmp/certificate.cert'
          dest: '{{ windows_exporter_tls_server_config.cert_file }}'
        - src: '/tmp/certificate.key'
          dest: '{{ windows_exporter_tls_server_config.key_file }}'
      loop_control:
        loop_var: cert

  roles:
    - role: antmelekhin.windows_exporter
