---
- name: 'Verify'
  hosts: all
  gather_facts: false

  tasks:
    - name: 'Check if Windows Exporter service is installed'
      ansible.windows.win_service:
        name: 'windows_exporter'
      register: __windows_exporter_service

    - name: 'Assert that Windows Exporter service is enabled and running'
      ansible.builtin.assert:
        that: "'running' in __windows_exporter_service.state"

    - name: 'Verify windows_exporter is responding to requests'
      ansible.builtin.uri:
        url: 'https://{{ ansible_host }}:9182/metrics'
        user: 'newuser1'
        password: 'newpassword1'
        force_basic_auth: true
        validate_certs: false
      delegate_to: localhost
      register: __windows_exporter_response
      until: __windows_exporter_response.status == 200
      retries: 120
      delay: 5
