---
- name: 'Verify'
  hosts: all
  gather_facts: false

  tasks:
    - name: 'Check if a windows_exporter service is installed'
      ansible.windows.win_service:
        name: 'windows_exporter'
      register: _windows_exporter_service

    - name: 'Assert that windows_exporter service is enabled and running'
      ansible.builtin.assert:
        that: _windows_exporter_service.state == 'running'

    - name: 'Verify windows_exporter is responding to requests'
      ansible.builtin.uri:
        url: 'https://{{ ansible_host }}:9182/metrics'
        user: 'newuser1'
        password: 'newpassword1'
        force_basic_auth: true
        validate_certs: false
      delegate_to: localhost
      register: _result
      until: _result.status == 200
      retries: 120
      delay: 5
