---
- name: 'Verify'
  hosts: all
  gather_facts: false

  tasks:
    - name: 'Check if a windows_exporter service is installed'
      ansible.windows.win_service:
        name: 'windows_exporter'
      register: __windows_exporter_service

    - name: 'Assert that windows_exporter service is enabled and running'
      ansible.builtin.assert:
        that: "'running' in __windows_exporter_service.state"

    - name: 'Verify windows_exporter is responding to requests'
      ansible.builtin.uri:
        url: 'http://{{ ansible_host }}:9182/metrics'
      delegate_to: localhost
      register: __result
      until: __result.status == 200
      retries: 120
      delay: 5
