---
- name: 'Verify'
  hosts: all
  gather_facts: false

  tasks:
    - name: 'Check if Windows Exporter service is installed'
      ansible.windows.win_service:
        name: 'windows_exporter'
      register: __windows_exporter_service

    - name: 'Assert that Windows Exporter service is enabled and running'
      ansible.builtin.assert:
        that: "'running' in __windows_exporter_service.state"

    - name: 'Verify the Windows Exporter is responding to requests'
      ansible.builtin.uri:
        url: 'http://{{ ansible_host }}:9182/metrics'
      delegate_to: localhost
      register: __windows_exporter_response
      until: __windows_exporter_response.status == 200
      retries: 120
      delay: 5

    - name: 'Check the current Windows Exporter version'
      ansible.windows.win_command:
        cmd: '"C:\Program Files\windows_exporter\windows_exporter.exe" --version'
      failed_when: false
      changed_when: false
      register: __windows_exporter_version_check

    - name: 'The Windows Exporter version output'
      ansible.builtin.debug:
        var: __windows_exporter_version_check.stderr_lines[0].split()[2]
