---
name: 'Molecule'
on:
  pull_request:
  push:
    branches: ['main']

jobs:
  lint:
    name: 'Lint'
    runs-on: 'ubuntu-22.04'
    steps:
      - name: 'Checkout the codebase'
        uses: 'actions/checkout@v4'

      - name: 'Set up Python 3'
        uses: 'actions/setup-python@v5'
        with:
          python-version: '3.x'

      - name: 'Install linters'
        run: pip3 install ansible-core==2.16.7 ansible-lint==24.5.0 yamllint==1.35.1

      - name: 'Run linters'
        run: |
          yamllint .
          ansible-lint
